workflows:
  android-apk:
    name: ManuForex AI - Build APK
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Compléter la structure Android manquante
        script: flutter create . --platforms=android --org com.manuforex
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build APK (debug, pour test rapide)
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
